services:
 - type: web
   name: flash-laughs-poster-maker
   env: node
   plan: free
   buildCommand: |
    npm install
    npm run build
   startCommand: npm start
   envVars:
    - key: NODE_VERSION
      value: 20
    - key: REMOVE_BG_API_KEY
      sync: false # set this secret in the Render dashboard
